name: IMSProg-build-macos-universal
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: read
jobs:
  build-IMSProg-macos-universal:
    runs-on: macos-26-intel
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          fetch-tags: true

      - name: clone REPO and compare versions
        run: |
          LatestPrebuiltReleasedVersionTag=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo $LatestPrebuiltReleasedVersionTag
          
          git clone https://github.com/bigbigmdm/IMSProg.git
          cd IMSProg
            LastReleasedVersionTag=$(git describe --tags --abbrev=0)
            commit_hash=$(git rev-list -n 1 "$LastReleasedVersionTag")
            version=$(echo "$LastReleasedVersionTag" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]' | sed 's/\.$//')
            echo "$version"

            echo "UPDATE_REPO=false" >> $GITHUB_ENV

            if [[ $(echo -e "$version\n$LatestPrebuiltReleasedVersionTag" | sort -V | head -n1) == "$LatestPrebuiltReleasedVersionTag" ]]; then
              git checkout $commit_hash
              echo "version=$version" >> $GITHUB_ENV
              echo "commit_hash=$commit_hash" >> $GITHUB_ENV
              echo "UPDATE_REPO=true" >> $GITHUB_ENV
            fi
          cd -
          
      - name: JSON to Variables
        if: env.UPDATE_REPO == 'true'
        uses: antifree/json-to-variables@v1.4.0
        with:
          filename: '.github/workflows/wf_pkg_vers.json'
          prefix: wf_pkg_vers

      - name: Install Build Essentials
        if: env.UPDATE_REPO == 'true'
        run: |
          brew install qt@${{ env.wf_pkg_vers_QT }} libftdi create-dmg
          # already installed:libusb cmake pkgconf
          HOST_ARCH=$(uname -m)
          echo HOST_ARCH=$HOST_ARCH     

      - name: Build IMSProg
        if: env.UPDATE_REPO == 'true'
        run: |
          echo "$(ls /Applications)"
          cd IMSProg
            ./build_all.sh
          cd -

      - name: Create DMG Package
        run: |
          mkdir artifacts && ARTIFACT_DIR="${PWD}/artifacts"
          echo "ARTIFACT_DIR=$ARTIFACT_DIR" >> $GITHUB_ENV
          VOLNAME="IMSProg_$version"
          IMSProgDMG="$VOLNAME.dmg"
          IMSProgZIP="$VOLNAME.zip"
          
          echo "VOLNAME=$VOLNAME" >> $GITHUB_ENV
          echo "IMSProgDMG=$IMSProgDMG" >> $GITHUB_ENV
          echo "IMSProgZIP=$IMSProgZIP" >> $GITHUB_ENV
          
          echo "VOLNAME=$VOLNAME"
          echo "IMSProgDMG=$IMSProgDMG"          
          echo "IMSProgZIP=$IMSProgZIP"

          cd $ARTIFACT_DIR
            ln -s /Applications Applications
            cp -R /Applications/IMSProg* .
            chmod +x *.app
          cd -
            
          create-dmg \
            --volname "$VOLNAME" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon "Applications" 450 180 \
            --hide-extension "Applications" \
            "$IMSProgDMG" \
            "$ARTIFACT_DIR"
          
          jar -cMf $ARTIFACT_DIR/$IMSProgZIP $IMSProgDMG 

      - name: Upload To Artifacts Dir
        if: env.UPDATE_REPO == 'true'
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ArtifactsDir
          path: ${{ env.ARTIFACT_DIR }}/*.dmg
          retention-days: 1

      - name: Trigger last Workflow per CLI
        if: env.UPDATE_REPO == 'true'
        run: |
          RUN_ID="${{ github.run_id }}"
          RUN_IDS="$RUN_IDS,$RUN_ID"
          gh workflow run .github/workflows/upload_artifacts.yaml \
          --field commit_hash="$commit_hash" \
          --field version="$version" \
          --field UPDATE_REPO="$UPDATE_REPO" \
          --field RUN_IDS="$RUN_IDS" \
          --ref ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
